uri_templates:
  [
    {
      'title': 'User Profile',
      'url': 'https://www.your-website.com/{{ticket.requester.email}}'
    },
    {
      'title': 'Reported Post',
      'url': 'https://www.your-website.com/post/{{ticket.customField:custom_field_name}}'
    }
  ]
