uri_templates:
  [
    {
      'title': 'Label for link 1',
      'url': 'https://www.sample-url.com/{{identifier from ticket}}'
    },
    {
      'title': 'User Profile',
      'url': 'https://www.your-website.com/{{ticket.requester.email}}'
    }
  ]
